// AUTO-GENERATED BY extract_videos.py
const ACADEMY_VIDEOS_EXTRACTED = [
    {
        "id": "ai-narrative-velocity-sentiment",
        "title": "Sentiment Analysis in Crypto Masterclass",
        "youtubeId": "bqOqAI7OD7Y",
        "thumb": "https://img.youtube.com/vi/bqOqAI7OD7Y/hqdefault.jpg",
        "desc": "Learn how to quantify social momentum and front-run hype cycles using advanced sentiment analysis techniques.",
        "route": "academy/ai-narrative-velocity-sentiment.html",
        "category": "AI Intelligence",
        "duration": "10:00"
    },
    {
        "id": "algorithmic-ai-trade-signals",
        "title": "AI for Trading: Algorithmic Signals",
        "youtubeId": "wYbf5XwdcPI",
        "thumb": "https://img.youtube.com/vi/wYbf5XwdcPI/hqdefault.jpg",
        "desc": "Learn how to leverage artificial intelligence and machine learning to generate high-probability trading signals.",
        "route": "academy/algorithmic-ai-trade-signals.html",
        "category": "AI Intelligence",
        "duration": "10:00"
    },
    {
        "id": "bollinger-bands-volatility",
        "title": "Mastering Bollinger Bands with SMB Capital",
        "youtubeId": "9q32G8yLxbM",
        "thumb": "https://img.youtube.com/vi/9q32G8yLxbM/hqdefault.jpg",
        "desc": "Learn how professional proprietary traders use Bollinger Bands to identify high-probability mean reversion and breakout ...",
        "route": "academy/bollinger-bands-volatility.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "breakout-trading-strategies",
        "title": "Institutional Breakout Trading Masterclass",
        "youtubeId": "wpPHULhcsn4",
        "thumb": "https://img.youtube.com/vi/wpPHULhcsn4/hqdefault.jpg",
        "desc": "Professional guide to trading volatility breakouts and avoiding fakeouts using order flow.",
        "route": "academy/breakout-trading-strategies.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "candlestick-patterns",
        "title": "Institutional Candlestick Analysis Masterclass",
        "youtubeId": "khy2uPMdK54",
        "thumb": "https://img.youtube.com/vi/khy2uPMdK54/hqdefault.jpg",
        "desc": "Learn how to read price action through candlesticks with an institutional perspective on supply and demand.",
        "route": "academy/candlestick-patterns.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "capital-sector-rotation",
        "title": "Sector Rotation Masterclass",
        "youtubeId": "C0BK_Mip9oM",
        "thumb": "https://img.youtube.com/vi/C0BK_Mip9oM/hqdefault.jpg",
        "desc": "Learn how to identify and front-run the rotation of capital across different crypto sectors.",
        "route": "academy/capital-sector-rotation.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "cme-futures-gaps-bitcoin",
        "title": "CME Bitcoin Futures Gaps Masterclass",
        "youtubeId": "ADSOBbXdzNE",
        "thumb": "https://img.youtube.com/vi/ADSOBbXdzNE/hqdefault.jpg",
        "desc": "Learn the mechanics of CME gaps, the arbitrage loop, and institutional weekend risk management.",
        "route": "academy/cme-futures-gaps-bitcoin.html",
        "category": "Macro",
        "duration": "10:00"
    },
    {
        "id": "crypto-liquidations-tracker",
        "title": "Crypto Liquidations & Open Interest Masterclass",
        "youtubeId": "rdaZDhciMxI",
        "thumb": "https://img.youtube.com/vi/rdaZDhciMxI/hqdefault.jpg",
        "desc": "Learn how to track institutional order flow and liquidation levels to identify market reversals.",
        "route": "academy/crypto-liquidations-tracker.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "divergence-trading-strategies",
        "title": "Institutional Divergence Trading Masterclass",
        "youtubeId": "uxNQDwjREuc",
        "thumb": "https://img.youtube.com/vi/uxNQDwjREuc/hqdefault.jpg",
        "desc": "Professional guide to identifying and trading regular and hidden divergences in crypto markets.",
        "route": "academy/divergence-trading-strategies.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "elliott-wave-theory",
        "title": "Elliott Wave Theory: The Definitive Guide",
        "youtubeId": "ZeD60UItVlM",
        "thumb": "https://img.youtube.com/vi/ZeD60UItVlM/hqdefault.jpg",
        "desc": "Master the fractal nature of markets with this institutional Elliott Wave masterclass.",
        "route": "academy/elliott-wave-theory.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "fibonacci-retracements-crypto",
        "title": "Institutional Fibonacci Masterclass",
        "youtubeId": "Ypj2VTWbrW0",
        "thumb": "https://img.youtube.com/vi/Ypj2VTWbrW0/hqdefault.jpg",
        "desc": "Learn how professional traders use Fibonacci levels to identify high-probability institutional entry zones.",
        "route": "academy/fibonacci-retracements-crypto.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "fundamental-mvrv-z-score",
        "title": "Mastering the Bitcoin MVRV Ratio",
        "youtubeId": "JisoL4rz9Wc",
        "thumb": "https://img.youtube.com/vi/JisoL4rz9Wc/hqdefault.jpg",
        "desc": "Learn how to use the MVRV Z-Score to identify macro market extremes and cycle tops/bottoms.",
        "route": "academy/fundamental-mvrv-z-score.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "harmonic-patterns-trading",
        "title": "Institutional Harmonic Patterns Masterclass",
        "youtubeId": "zSWK51YNwKs",
        "thumb": "https://img.youtube.com/vi/zSWK51YNwKs/hqdefault.jpg",
        "desc": "Learn how to trade Gartley, Bat, and Butterfly patterns using institutional execution standards.",
        "route": "academy/harmonic-patterns-trading.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "hidden-markov-market-regimes",
        "title": "Institutional Guide to Market Regime Classification",
        "youtubeId": "bDRtjBsx1ng",
        "thumb": "https://img.youtube.com/vi/bDRtjBsx1ng/hqdefault.jpg",
        "desc": "Learn how professional quant desks use probabilistic models to identify shifting market regimes and adapt their trading ...",
        "route": "academy/hidden-markov-market-regimes.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "how-to-set-proper-stop-loss",
        "title": "Institutional Risk Management Masterclass",
        "youtubeId": "749DyLprirs",
        "thumb": "https://img.youtube.com/vi/749DyLprirs/hqdefault.jpg",
        "desc": "Learn the professional methodology for setting stop losses and managing risk-to-reward ratios.",
        "route": "academy/how-to-set-proper-stop-loss.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "ichimoku-cloud-strategy",
        "title": "Institutional Ichimoku Cloud Masterclass",
        "youtubeId": "O5oortK3IAE",
        "thumb": "https://img.youtube.com/vi/O5oortK3IAE/hqdefault.jpg",
        "desc": "Professional guide to mastering the Ichimoku Kinko Hyo system for trend and momentum analysis.",
        "route": "academy/ichimoku-cloud-strategy.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "importance-of-trading-journal",
        "title": "Institutional Trading Journal Masterclass",
        "youtubeId": "0v7L4J5b-n0",
        "thumb": "https://img.youtube.com/vi/0v7L4J5b-n0/hqdefault.jpg",
        "desc": "Learn how to quantify your edge and audit your performance using institutional-grade trade logging.",
        "route": "academy/importance-of-trading-journal.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "institutional-yield-farming",
        "title": "Institutional DeFi Yield Farming Masterclass",
        "youtubeId": "ClnnLI1SClA",
        "thumb": "https://img.youtube.com/vi/ClnnLI1SClA/hqdefault.jpg",
        "desc": "Learn how to optimize risk-adjusted returns and manage liquidity in decentralized finance protocols.",
        "route": "academy/institutional-yield-farming.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "mastering-risk-to-reward-ratio",
        "title": "Institutional Risk Management Masterclass",
        "youtubeId": "5G1g0w6eW5I",
        "thumb": "https://img.youtube.com/vi/5G1g0w6eW5I/hqdefault.jpg",
        "desc": "Learn the professional methodology for maintaining positive expectancy through asymmetric risk-to-reward ratios.",
        "route": "academy/mastering-risk-to-reward-ratio.html",
        "category": "Risk Management",
        "duration": "10:00"
    },
    {
        "id": "on-chain-whale-tracking",
        "title": "On-chain Analytics & Whale Tracking Masterclass",
        "youtubeId": "XSJnX9oe_is",
        "thumb": "https://img.youtube.com/vi/XSJnX9oe_is/hqdefault.jpg",
        "desc": "Institutional-grade webinar on mastering the MVRV ratio and other on-chain analytics to identify market extremes.",
        "route": "academy/on-chain-whale-tracking.html",
        "category": "On-Chain",
        "duration": "10:00"
    },
    {
        "id": "options-flow-dark-pools",
        "title": "Institutional Options Flow & Dark Pools with SpotGamma",
        "youtubeId": "3cM7toFnRTU",
        "thumb": "https://img.youtube.com/vi/3cM7toFnRTU/hqdefault.jpg",
        "desc": "Learn how to track institutional dark pool prints and options flow to identify major market support and resistance level...",
        "route": "academy/options-flow-dark-pools.html",
        "category": "Options Alpha",
        "duration": "10:00"
    },
    {
        "id": "options-implied-volatility-smile",
        "title": "The Volatility Smile Explained",
        "youtubeId": "Lza68h8Tlpg",
        "thumb": "https://img.youtube.com/vi/Lza68h8Tlpg/hqdefault.jpg",
        "desc": "Learn how to interpret the volatility smile and implied volatility skew for professional options trading.",
        "route": "academy/options-implied-volatility-smile.html",
        "category": "Options Alpha",
        "duration": "10:00"
    },
    {
        "id": "order-blocks-institutional",
        "title": "Institutional Order Blocks Masterclass",
        "youtubeId": "f18gazn0nYE",
        "thumb": "https://img.youtube.com/vi/f18gazn0nYE/hqdefault.jpg",
        "desc": "Learn how to identify institutional supply and demand zones using Order Block mechanics.",
        "route": "academy/order-blocks-institutional.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "order-book-liquidity-heatmaps",
        "title": "Order Book Liquidity Heatmaps Masterclass",
        "youtubeId": "DmXeCNPw2g4",
        "thumb": "https://img.youtube.com/vi/DmXeCNPw2g4/hqdefault.jpg",
        "desc": "Learn how to read institutional liquidity heatmaps and identify where major market participants are positioning their li...",
        "route": "academy/order-book-liquidity-heatmaps.html",
        "category": "Order Flow",
        "duration": "10:00"
    },
    {
        "id": "pairs-trading-crypto-arbitrage",
        "title": "The Correlation Matrix & Macro Assets",
        "youtubeId": "4oa5chIYDcM",
        "thumb": "https://img.youtube.com/vi/4oa5chIYDcM/hqdefault.jpg",
        "desc": "Learn how to use correlation matrices to identify institutional rotation and hedge directional risk.",
        "route": "academy/pairs-trading-crypto-arbitrage.html",
        "category": "AI Intelligence",
        "duration": "10:00"
    },
    {
        "id": "position-sizing-and-leverage",
        "title": "Mastering Position Sizing and Risk Management",
        "youtubeId": "q5UiDAk1740",
        "thumb": "https://img.youtube.com/vi/q5UiDAk1740/hqdefault.jpg",
        "desc": "Professional guide to calculating optimal position sizes, managing leverage, and protecting capital using institutional ...",
        "route": "academy/position-sizing-and-leverage.html",
        "category": "Risk Management",
        "duration": "10:00"
    },
    {
        "id": "price-action-trading-naked",
        "title": "Naked Price Action Masterclass: Reading Institutional Flow",
        "youtubeId": "FRHE-ft4dVo",
        "thumb": "https://img.youtube.com/vi/FRHE-ft4dVo/hqdefault.jpg",
        "desc": "Learn how professional traders read raw market structure and institutional liquidity without relying on lagging indicato...",
        "route": "academy/price-action-trading-naked.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "rsi-macd-momentum-oscillators",
        "title": "Momentum Masterclass: RSI and MACD",
        "youtubeId": "t6HCSzlSuNk",
        "thumb": "https://img.youtube.com/vi/t6HCSzlSuNk/hqdefault.jpg",
        "desc": "Learn how to use RSI and MACD for high-confluence momentum trading.",
        "route": "academy/rsi-macd-momentum-oscillators.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "smart-money-concepts-smc",
        "title": "Institutional SMC Masterclass",
        "youtubeId": "FNUeYlhbXkU",
        "thumb": "https://img.youtube.com/vi/FNUeYlhbXkU/hqdefault.jpg",
        "desc": "Learn the core principles of Smart Money Concepts (SMC) including order blocks, liquidity sweeps, and market structure s...",
        "route": "academy/smart-money-concepts-smc.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "stablecoin-macro-liquidity-flows",
        "title": "Institutional Guide to Stablecoin Macro Liquidity",
        "youtubeId": "t0GU36MA04k",
        "thumb": "https://img.youtube.com/vi/t0GU36MA04k/hqdefault.jpg",
        "desc": "Deep dive into tracking stablecoin supply flows, mint events, and CEX inflows as a leading indicator for Bitcoin market ...",
        "route": "academy/stablecoin-macro-liquidity-flows.html",
        "category": "Order Flow",
        "duration": "10:00"
    },
    {
        "id": "statistical-mean-reversion-z-scores",
        "title": "Institutional Mean Reversion & Z-Scores Masterclass",
        "youtubeId": "c2j-zs8YN3c",
        "thumb": "https://img.youtube.com/vi/c2j-zs8YN3c/hqdefault.jpg",
        "desc": "Advanced guide to trading statistical mean reversion using Z-Scores and standard deviation.",
        "route": "academy/statistical-mean-reversion-z-scores.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "support-and-resistance-fundamentals",
        "title": "Mastering Support and Resistance: The Institutional Framework",
        "youtubeId": "nuVv0ZWUfs4",
        "thumb": "https://img.youtube.com/vi/nuVv0ZWUfs4/hqdefault.jpg",
        "desc": "Learn how to identify structural supply and demand zones, map volume profile confluence, and avoid retail stop-run traps...",
        "route": "academy/support-and-resistance-fundamentals.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "token-unlocks-supply-dilution",
        "title": "Institutional Guide to Token Unlocks & Supply Shocks",
        "youtubeId": "ZL1bysb2MV0",
        "thumb": "https://img.youtube.com/vi/ZL1bysb2MV0/hqdefault.jpg",
        "desc": "Master the mechanics of vesting cliffs, linear unlocks, and how to identify high-probability short-selling opportunities...",
        "route": "academy/token-unlocks-supply-dilution.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "trading-moving-average-crossovers",
        "title": "Institutional Moving Averages Masterclass",
        "youtubeId": "cSWC2WwbhHE",
        "thumb": "https://img.youtube.com/vi/cSWC2WwbhHE/hqdefault.jpg",
        "desc": "Learn how to use SMA and EMA crossovers to confirm macro trends in crypto markets.",
        "route": "academy/trading-moving-average-crossovers.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "trading-psychology-fomo-panic",
        "title": "Institutional Trading Psychology Masterclass",
        "youtubeId": "bEXz7Abf-wM",
        "thumb": "https://img.youtube.com/vi/bEXz7Abf-wM/hqdefault.jpg",
        "desc": "Master the emotional extremes of trading: Fear, Greed, and FOMO, with institutional-grade psychological frameworks.",
        "route": "academy/trading-psychology-fomo-panic.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "trendlines-and-channels",
        "title": "Institutional Trendlines & Channels Masterclass",
        "youtubeId": "joPxq3IB8tk",
        "thumb": "https://img.youtube.com/vi/joPxq3IB8tk/hqdefault.jpg",
        "desc": "Professional guide to drawing trendlines and channels using institutional momentum logic.",
        "route": "academy/trendlines-and-channels.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "understanding-gamma-exposure-gex",
        "title": "Market Maker Mechanics: Gamma Exposure (GEX) Decoded",
        "youtubeId": "xWLx3vPfe7U",
        "thumb": "https://img.youtube.com/vi/xWLx3vPfe7U/hqdefault.jpg",
        "desc": "Understand how options market maker hedging drives price volatility and trend acceleration.",
        "route": "academy/understanding-gamma-exposure-gex.html",
        "category": "Options Alpha",
        "duration": "10:00"
    },
    {
        "id": "volume-profile-market-profile",
        "title": "Institutional Volume Profile: The Auction Process",
        "youtubeId": "uDzqh0c6BeM",
        "thumb": "https://img.youtube.com/vi/uDzqh0c6BeM/hqdefault.jpg",
        "desc": "Master the Volume Profile and Auction Market Theory to identify high-probability institutional zones.",
        "route": "academy/volume-profile-market-profile.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "vwap-institutional-execution",
        "title": "Institutional VWAP Trading Strategy",
        "youtubeId": "cYN4ZgGvR84",
        "thumb": "https://img.youtube.com/vi/cYN4ZgGvR84/hqdefault.jpg",
        "desc": "Learn how institutional desks use Volume Weighted Average Price (VWAP) for execution and mean reversion.",
        "route": "academy/vwap-institutional-execution.html",
        "category": "Strategy",
        "duration": "10:00"
    },
    {
        "id": "wyckoff-method-accumulation-distribution",
        "title": "Institutional Wyckoff Method Masterclass",
        "youtubeId": "VB52gdM0kLE",
        "thumb": "https://img.youtube.com/vi/VB52gdM0kLE/hqdefault.jpg",
        "desc": "Learn the phases of accumulation and distribution using the Wyckoff methodology.",
        "route": "academy/wyckoff-method-accumulation-distribution.html",
        "category": "Strategy",
        "duration": "10:00"
    }
];