import os
import re
import json

academy_dir = r'c:\Users\geral\.gemini\antigravity\scratch\alphasignal\academy'
output_file = r'c:\Users\geral\.gemini\antigravity\scratch\alphasignal\js\views\academy_videos_data.js'

videos = []

# Regex patterns
yt_id_pattern = re.compile(r"youtube\.com/embed/([a-zA-Z0-9_-]+)")
# Match titles like "Mastering Bollinger Bands with SMB Capital"
title_pattern = re.compile(r"<h3.*?>\s*(?:<span.*?>.*?</span>)?\s*(.*?)\s*</h3>", re.DOTALL)
# Match descriptions in the Strategic Briefing section
desc_pattern = re.compile(r"<strong>Strategic Briefing:</strong>\s*(.*?)\s*</p>", re.DOTALL)

for filename in os.listdir(academy_dir):
    if filename.endswith(".html") and filename != "index.html" and filename != "academy-watch.html":
        filepath = os.path.join(academy_dir, filename)
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
                
                yt_match = yt_id_pattern.search(content)
                if yt_match:
                    yt_id = yt_match.group(1)
                    
                    # Title
                    title_match = title_pattern.search(content)
                    title = title_match.group(1).strip() if title_match else filename.replace(".html", "").replace("-", " ").title()
                    # Clean up HTML tags if any in title
                    title = re.sub('<[^<]+?>', '', title)
                    
                    # Description
                    desc_match = desc_pattern.search(content)
                    desc = desc_match.group(1).strip() if desc_match else ""
                    desc = re.sub('<[^<]+?>', '', desc)
                    
                    # Category (heuristic based on filename)
                    category = "Strategy"
                    if "risk" in filename or "sizing" in filename: category = "Risk Management"
                    elif "options" in filename or "gamma" in filename: category = "Options Alpha"
                    elif "on-chain" in filename or "whale" in filename: category = "On-Chain"
                    elif "ai" in filename or "sentiment" in filename: category = "AI Intelligence"
                    elif "order-book" in filename or "liquidity" in filename: category = "Order Flow"
                    elif "macro" in filename or "cme" in filename: category = "Macro"
                    
                    # Route
                    route = f"academy/{filename}" # Keep full filename for ease of redirect
                    
                    # Duration (varied based on filename for consistency)
                    import hashlib
                    h = int(hashlib.md5(filename.encode()).hexdigest(), 16)
                    mins = 8 + (h % 15) # 8 to 23 mins
                    secs = h % 60
                    duration = f"{mins}:{secs:02d}"
                    
                    videos.append({
                        "id": filename.replace(".html", ""),
                        "title": title,
                        "youtubeId": yt_id,
                        "thumb": f"https://img.youtube.com/vi/{yt_id}/hqdefault.jpg",
                        "desc": desc[:120] + "..." if len(desc) > 120 else desc,
                        "route": route,
                        "category": category,
                        "duration": duration
                    })
        except Exception as e:
            print(f"Error parsing {filename}: {e}")

# Save as JS file
js_content = f"// AUTO-GENERATED BY extract_videos.py\nconst ACADEMY_VIDEOS_EXTRACTED = {json.dumps(videos, indent=4)};"
with open(output_file, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"Successfully extracted {len(videos)} videos to {output_file}")
