
async function renderBlockRadar(tabs = null) {
    if (!tabs) tabs = window.analyticsHubTabs;
    appEl.innerHTML = skeleton(5);
    
    // Initial fetch
    const data = await fetchAPI('/whales');
    if (!data) return;

    appEl.innerHTML = `
        <div class="view-header" style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:10px;">
            <div>
                <h2 style="font-size:0.65rem;font-weight:900;letter-spacing:2px;color:var(--text-dim);text-transform:uppercase;margin:0 0 4px">Analytics Hub</h2>
                <h1><span class="material-symbols-outlined" style="vertical-align:middle;margin-right:8px;color:var(--accent); animation: radar-pulse 2s infinite">biotech</span>Whale Block Radar <span class="premium-badge">REAL-TIME</span></h1>
                <p>Monitoring high-conviction institutional execution across core exchange orderbooks.</p>
            </div>
            <div style="display:flex;gap:8px;flex-wrap:wrap">
                <button class="intel-action-btn mini" onclick="renderWhales()" style="width:auto;padding:4px 12px;font-size:0.6rem;display:flex;align-items:center;gap:4px">
                    <span class="material-symbols-outlined" style="font-size:13px">waves</span> WHALE PULSE
                </button>
                <button class="intel-action-btn mini outline" style="width:auto;padding:4px 10px;font-size:0.6rem;display:flex;align-items:center;gap:4px" onclick="switchView('docs-block-radar')">
                    <span class="material-symbols-outlined" style="font-size:13px">help</span> DOCS
                </button>
            </div>
        </div>
        ${tabs ? renderHubTabs('block-radar', tabs) : ''}

        <div class="radar-container" style="display:grid; grid-template-columns: 1fr 400px; gap:2rem; margin-top:1rem">
            
            <div class="block-tape-section">
                <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:1.5rem">
                    <h3 style="margin:0; font-size:0.85rem; color:var(--text); letter-spacing:1px">INSTITUTIONAL EXECUTION TAPE</h3>
                    <div style="display:flex; align-items:center; gap:10px">
                        <span style="font-size:0.6rem; color:var(--text-dim)">THRESHOLD: >$50K</span>
                        <div class="status-dot pulse"></div>
                        <span style="font-size:0.6rem; color:var(--accent)">LIVE FEED</span>
                    </div>
                </div>
                
                <div id="block-radar-list" class="whale-list" style="max-height: 800px; overflow-y: auto; padding-right: 8px">
                    ${renderBlockRadarRows(data.results)}
                </div>
            </div>

            <div class="radar-intel-sidebar">
                <div class="glass-card" style="padding:1.5rem; margin-bottom:1.5rem">
                    <h3 style="font-size:0.75rem; color:var(--accent); margin-bottom:1rem">RADAR STATISTICS (24H)</h3>
                    <div style="display:flex; flex-direction:column; gap:15px">
                        <div style="display:flex; justify-content:space-between">
                            <span style="font-size:0.7rem; color:var(--text-dim)">TOTAL BLOCK VOLUME</span>
                            <span id="total-block-vol" style="font-size:0.8rem; font-weight:900; color:var(--text)">$0.0M</span>
                        </div>
                        <div style="display:flex; justify-content:space-between">
                            <span style="font-size:0.7rem; color:var(--text-dim)">BUY PRESSURE (BLOCK)</span>
                            <span id="buy-pressure-pct" style="font-size:0.8rem; font-weight:900; color:var(--risk-low)">0%</span>
                        </div>
                        <div style="display:flex; justify-content:space-between">
                            <span style="font-size:0.7rem; color:var(--text-dim)">LARGEST EXECUTION</span>
                            <span id="max-block-val" style="font-size:0.8rem; font-weight:900; color:var(--accent)">$0.0M</span>
                        </div>
                    </div>
                </div>

                <div class="glass-card" style="padding:1.5rem">
                    <h3 style="font-size:0.75rem; color:var(--text-dim); margin-bottom:1rem">EXECUTION HEATMAP</h3>
                    <div id="block-radar-heatmap" style="height: 300px; display: flex; flex-direction: column; gap: 8px">
                        <!-- Heatmap generated by JS -->
                    </div>
                </div>
            </div>

        </div>

        <style>
            @keyframes radar-pulse {
                0% { opacity: 1; transform: scale(1); }
                50% { opacity: 0.5; transform: scale(1.1); }
                100% { opacity: 1; transform: scale(1); }
            }
            .block-radar-row {
                background: rgba(255,255,255,0.02);
                border: 1px solid rgba(255,255,255,0.05);
                border-radius: 8px;
                padding: 1rem;
                margin-bottom: 0.8rem;
                display: flex;
                align-items: center;
                gap: 1.5rem;
                transition: all 0.3s ease;
                position: relative;
                overflow: hidden;
            }
            .block-radar-row:hover {
                border-color: var(--accent);
                background: rgba(0,242,255,0.03);
                transform: translateX(5px);
            }
            .block-radar-row.extreme {
                border-color: rgba(139,92,246,0.3);
                background: linear-gradient(90deg, rgba(139,92,246,0.05), transparent);
            }
            .br-ticker {
                width: 50px;
                font-weight: 900;
                font-family: 'JetBrains Mono';
                color: var(--text);
                font-size: 0.9rem;
            }
            .br-side {
                width: 60px;
                font-size: 0.65rem;
                font-weight: 900;
                letter-spacing: 1px;
                padding: 4px 8px;
                border-radius: 4px;
                text-align: center;
            }
            .br-side.buy { background: rgba(34,197,94,0.1); color: var(--risk-low); border: 1px solid rgba(34,197,94,0.2); }
            .br-side.sell { background: rgba(239,68,68,0.1); color: var(--risk-high); border: 1px solid rgba(239,68,68,0.2); }
            
            .br-value {
                flex: 1;
                font-size: 1.1rem;
                font-weight: 900;
                color: var(--text);
                font-family: 'JetBrains Mono';
            }
            .br-impact-meter {
                width: 100px;
                height: 4px;
                background: rgba(255,255,255,0.05);
                border-radius: 2px;
                position: relative;
            }
            .br-impact-bar {
                height: 100%;
                border-radius: 2px;
                background: var(--accent);
            }
            .br-meta {
                font-size: 0.65rem;
                color: var(--text-dim);
                display: flex;
                flex-direction: column;
                align-items: flex-end;
                gap: 4px;
            }
        </style>
    `;

    updateRadarStats(data.results);
    renderRadarHeatmap(data.results);

    // Setup Polling
    if (window.blockRadarInterval) clearInterval(window.blockRadarInterval);
    window.blockRadarInterval = setInterval(async () => {
        const newData = await fetchAPI('/whales');
        if (newData && newData.results) {
            const listEl = document.getElementById('block-radar-list');
            if (listEl) {
                listEl.innerHTML = renderBlockRadarRows(newData.results);
                updateRadarStats(newData.results);
                renderRadarHeatmap(newData.results);
            }
        }
    }, 10000);
}

function renderBlockRadarRows(results) {
    if (!results || results.length === 0) return '<div style="color:var(--text-dim); text-align:center; padding:2rem">NO BLOCKS DETECTED IN LAST 5 MINUTES</div>';
    
    return results.map(w => {
        const isExtreme = w.impact === 'EXTREME';
        const impactPct = w.impact === 'EXTREME' ? 100 : w.impact === 'HIGH' ? 70 : 40;
        const sideVal = w.side || 'BUY';
        const sideClass = sideVal.toLowerCase();
        
        return `
            <div class="block-radar-row ${isExtreme ? 'extreme' : ''}">
                <div class="br-ticker">${w.ticker || 'BTC'}</div>
                <div class="br-side ${sideClass}">${sideVal}</div>
                <div class="br-value">${w.usdValue}</div>
                <div style="display:flex; flex-direction:column; gap:4px">
                    <span style="font-size:0.55rem; color:var(--text-dim); letter-spacing:1px">${w.impact} IMPACT</span>
                    <div class="br-impact-meter">
                        <div class="br-impact-bar" style="width:${impactPct}%"></div>
                    </div>
                </div>
                <div class="br-meta">
                    <span style="color:var(--text)">${w.timestamp}</span>
                    <span style="color:var(--text-dim); font-size:0.55rem">@ ${formatPrice(w.price)}</span>
                </div>
            </div>
        `;
    }).join('');
}

function updateRadarStats(results) {
    if (!results || results.length === 0) return;
    
    let totalVol = 0;
    let buyVol = 0;
    let maxVal = 0;
    
    results.forEach(w => {
        // Parse USD value string like "$1.2M" or "$50,000"
        let val = 0;
        if (w.usdValue.includes('M')) {
            val = parseFloat(w.usdValue.replace('$', '').replace('M', '')) * 1000000;
        } else {
            val = parseFloat(w.usdValue.replace('$', '').replace(/,/g, ''));
        }
        
        totalVol += val;
        if ((w.side || 'BUY').toUpperCase() === 'BUY') buyVol += val;
        if (val > maxVal) maxVal = val;
    });

    const totalEl = document.getElementById('total-block-vol');
    const buyEl = document.getElementById('buy-pressure-pct');
    const maxEl = document.getElementById('max-block-val');
    
    if (totalEl) totalEl.textContent = `$${(totalVol / 1000000).toFixed(2)}M`;
    if (buyEl) {
        const pct = (buyVol / totalVol * 100).toFixed(1);
        buyEl.textContent = `${pct}%`;
        buyEl.style.color = parseFloat(pct) > 50 ? 'var(--risk-low)' : 'var(--risk-high)';
    }
    if (maxEl) maxEl.textContent = `$${(maxVal / 1000000).toFixed(2)}M`;
}

function renderRadarHeatmap(results) {
    const container = document.getElementById('block-radar-heatmap');
    if (!container) return;
    
    const tickerBuckets = {};
    results.forEach(w => {
        tickerBuckets[w.ticker] = (tickerBuckets[w.ticker] || 0) + 1;
    });
    
    const sorted = Object.entries(tickerBuckets).sort((a,b) => b[1] - a[1]);
    const max = sorted[0]?.[1] || 1;
    
    container.innerHTML = sorted.map(([ticker, count]) => {
        const pct = (count / max * 100);
        return `
            <div style="display:flex; align-items:center; gap:10px">
                <span style="width:40px; font-size:0.65rem; color:var(--text); font-weight:900">${ticker}</span>
                <div style="flex:1; height:8px; background:rgba(255,255,255,0.05); border-radius:4px; overflow:hidden">
                    <div style="width:${pct}%; height:100%; background:var(--accent); opacity:${0.3 + (pct/100)*0.7}"></div>
                </div>
                <span style="font-size:0.6rem; color:var(--text-dim); width:20px">${count}</span>
            </div>
        `;
    }).join('');
}
