events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    server {
        listen 80;
        server_name localhost api.docforge.local;

        location / {
            proxy_pass http://docforge-api:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /studio {
            proxy_pass http://docforge-studio:4001/;
            proxy_set_header Host $host;
        }

        location /landing {
            proxy_pass http://docforge-landing:4002/;
            proxy_set_header Host $host;
        }
    }
}
